[tool.poetry]
name = "space-invaders-pygame"
version = "0.1.0"
description = ""
authors = ["aquaskygod <jfeaw1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
